// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-BgEWswvNUl3CCfgRO4nh4SVlxhQYYWs',
    appId: '1:795857611522:web:94662178404fe35089f01b',
    messagingSenderId: '795857611522',
    projectId: 'chat-app-1-f6eaf',
    authDomain: 'chat-app-1-f6eaf.firebaseapp.com',
    storageBucket: 'chat-app-1-f6eaf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMXVDp50wfV8mUAXInbp2zANvVdqJm-Lk',
    appId: '1:795857611522:android:f0140b132c5856fd89f01b',
    messagingSenderId: '795857611522',
    projectId: 'chat-app-1-f6eaf',
    storageBucket: 'chat-app-1-f6eaf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYCNBCYIMoYUt44R6xiShhPGeSRf8s1so',
    appId: '1:795857611522:ios:31f50d0870c3c1c589f01b',
    messagingSenderId: '795857611522',
    projectId: 'chat-app-1-f6eaf',
    storageBucket: 'chat-app-1-f6eaf.appspot.com',
    iosBundleId: 'com.example.chatCustomer',
  );
}
